// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF NS Selection
 *
 * NSSF Network Slice Selection Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strconv"
	"strings"

	"github.com/omec-project/nssf/logger"
	stats "github.com/omec-project/nssf/metrics"
	"github.com/omec-project/nssf/plugin"
	"github.com/omec-project/nssf/util"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

func hasExplodedQueryParam(query url.Values, prefix string) bool {
	for key := range query {
		if strings.HasPrefix(key, prefix+"[") {
			return true
		}
	}
	return false
}

func parseExplodedSnssai(query url.Values, prefix string) (models.Snssai, bool, error) {
	var snssai models.Snssai
	var found bool

	if sst := query.Get(prefix + "[sst]"); sst != "" {
		sstValue, err := strconv.ParseInt(sst, 10, 32)
		if err != nil {
			return snssai, false, err
		}
		snssai.Sst = int32(sstValue)
		found = true
	}
	if sd := query.Get(prefix + "[sd]"); sd != "" {
		snssai.Sd = &sd
		found = true
	}

	return snssai, found, nil
}

// Parse NSSelectionGet query parameter
func parseQueryParameter(query url.Values) (plugin.NsselectionQueryParameter, error) {
	var (
		param plugin.NsselectionQueryParameter
		err   error
	)

	if query.Get("nf-type") != "" {
		nfType := models.NFType(query.Get("nf-type"))
		param.NfType = &nfType
	}

	param.NfId = query.Get("nf-id")

	if query.Get("slice-info-request-for-registration") != "" {
		param.SliceInfoRequestForRegistration = models.NewSliceInfoForRegistration()
		err = json.NewDecoder(strings.NewReader(
			query.Get("slice-info-request-for-registration"))).Decode(param.SliceInfoRequestForRegistration)
		if err != nil {
			return param, err
		}
	}

	if query.Get("slice-info-request-for-pdu-session") != "" {
		param.SliceInfoRequestForPduSession = models.NewSliceInfoForPDUSessionWithDefaults()
		err = json.NewDecoder(strings.NewReader(
			query.Get("slice-info-request-for-pdu-session"))).Decode(param.SliceInfoRequestForPduSession)
		if err != nil {
			return param, err
		}
	} else if hasExplodedQueryParam(query, "slice-info-request-for-pdu-session") {
		param.SliceInfoRequestForPduSession = models.NewSliceInfoForPDUSessionWithDefaults()
		if snssai, found, parseErr := parseExplodedSnssai(query, "slice-info-request-for-pdu-session[sNssai]"); parseErr != nil {
			return param, parseErr
		} else if found {
			param.SliceInfoRequestForPduSession.SNssai = snssai
		}
		if roamingIndication := query.Get("slice-info-request-for-pdu-session[roamingIndication]"); roamingIndication != "" {
			param.SliceInfoRequestForPduSession.RoamingIndication = models.RoamingIndication(roamingIndication)
		}
		if homeSnssai, found, parseErr := parseExplodedSnssai(query, "slice-info-request-for-pdu-session[homeSnssai]"); parseErr != nil {
			return param, parseErr
		} else if found {
			param.SliceInfoRequestForPduSession.HomeSnssai = &homeSnssai
		}
	}

	if query.Get("home-plmn-id") != "" {
		param.HomePlmnId = models.NewPlmnIdWithDefaults()
		err = json.NewDecoder(strings.NewReader(query.Get("home-plmn-id"))).Decode(param.HomePlmnId)
		if err != nil {
			return param, err
		}
	}

	if query.Get("tai") != "" {
		param.Tai = models.NewTaiWithDefaults()
		err = json.NewDecoder(strings.NewReader(query.Get("tai"))).Decode(param.Tai)
		if err != nil {
			return param, err
		}
	}

	if query.Get("supported-features") != "" {
		param.SupportedFeatures = query.Get("supported-features")
	}

	return param, err
}

// Check if the NF service consumer is authorized
// TODO: Check if the NF service consumer is legal with local configuration, or possibly after querying NRF through `nf-id` e.g. Whether the V-NSSF is authorized
func checkNfServiceConsumer(nfType models.NFType) error {
	if nfType != models.NFTYPE_AMF && nfType != models.NFTYPE_NSSF {
		return fmt.Errorf("`nf-type`:'%s' is not authorized to retrieve the slice selection information", string(nfType))
	}

	return nil
}

// NSSelectionGet - Retrieve the Network Slice Selection Information
func HandleNSSelectionGet(request *httpwrapper.Request) *httpwrapper.Response {
	logger.Nsselection.Infof("Handle NSSelectionGet")

	query := request.Query

	response, problemDetails := NSSelectionGetProcedure(query)

	nfType := GetNfTypeFromQueryParameters(query)
	nfId := GetNfIdFromQueryParameters(query)

	if response != nil {
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "SUCCESS")
		return httpwrapper.NewResponse(http.StatusOK, nil, response)
	} else if problemDetails != nil {
		stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
		return httpwrapper.NewResponse(int(problemDetails.GetStatus()), nil, problemDetails)
	}
	problemDetails = utils.ProblemDetailsUnspecified()
	stats.IncrementNssfNsSelectionsStats(nfType, nfId, "FAILURE")
	return httpwrapper.NewResponse(http.StatusForbidden, nil, problemDetails)
}

func NSSelectionGetProcedure(query url.Values) (*models.AuthorizedNetworkSliceInfo, *models.ProblemDetails) {
	var (
		status         int
		response       *models.AuthorizedNetworkSliceInfo
		problemDetails *models.ProblemDetails
	)
	response = &models.AuthorizedNetworkSliceInfo{}
	problemDetails = &models.ProblemDetails{}

	// TODO: Record request times of the NF service consumer and response with ProblemDetails of 429 Too Many Requests
	//       if the consumer has sent too many requests in a configured amount of time
	// TODO: Check URI length and response with ProblemDetails of 414 URI Too Long if URI is too long

	// Parse query parameter
	param, err := parseQueryParameter(query)
	if err != nil {
		problemDetail := "[Query Parameter] " + err.Error()
		logger.Nsselection.Errorln(problemDetail)
		problemDetails = utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		return nil, problemDetails
	}

	// Check permission of NF service consumer
	if param.NfType == nil {
		problemDetail := "[Query Parameter] `nf-type` is required"
		problemDetails = models.NewProblemDetails()
		problemDetails.SetTitle(util.INVALID_REQUEST)
		problemDetails.SetStatus(http.StatusBadRequest)
		problemDetails.SetDetail(problemDetail)
		invalidParams := []models.InvalidParam{{
			Param:  "nf-type",
			Reason: &problemDetail,
		}}
		problemDetails.SetInvalidParams(invalidParams)
		return nil, problemDetails
	}

	err = checkNfServiceConsumer(*param.NfType)
	if err != nil {
		// status = http.StatusForbidden
		problemDetails = models.NewProblemDetails()
		problemDetails.SetTitle(util.UNAUTHORIZED_CONSUMER)
		problemDetails.SetStatus(http.StatusForbidden)
		problemDetails.SetDetail(err.Error())
		return nil, problemDetails
	}

	if param.SliceInfoRequestForRegistration == nil && param.SliceInfoRequestForPduSession == nil {
		problemDetail := "[Query Parameter] one of `slice-info-request-for-registration` or `slice-info-request-for-pdu-session` is required"
		problemDetails = models.NewProblemDetails()
		problemDetails.SetTitle(util.INVALID_REQUEST)
		problemDetails.SetStatus(http.StatusBadRequest)
		problemDetails.SetDetail(problemDetail)
		invalidParams := []models.InvalidParam{
			{Param: "slice-info-request-for-registration", Reason: &problemDetail},
			{Param: "slice-info-request-for-pdu-session", Reason: &problemDetail},
		}
		problemDetails.SetInvalidParams(invalidParams)
		return nil, problemDetails
	}

	if param.SliceInfoRequestForRegistration != nil {
		// Network slice information is requested during the Registration procedure
		status = nsselectionForRegistration(param, response, problemDetails)
	} else {
		// Network slice information is requested during the PDU session establishment procedure
		status = nsselectionForPduSession(param, response, problemDetails)
	}

	if status != http.StatusOK {
		return nil, problemDetails
	}
	return response, nil
}

func GetNfTypeFromQueryParameters(query url.Values) (nfType string) {
	if query.Get("nf-type") != "" {
		return query.Get("nf-type")
	}
	return "UNKNOWN_NF"
}

func GetNfIdFromQueryParameters(query url.Values) (nfId string) {
	if query.Get("nf-id") != "" {
		return query.Get("nf-id")
	}
	return "UNKNOWN_NF_ID"
}
