// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF NSSAI Availability
 *
 * NSSF NSSAI Availability Service
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package producer

import (
	"net/http"

	"github.com/omec-project/nssf/logger"
	stats "github.com/omec-project/nssf/metrics"
	"github.com/omec-project/openapi/models"
	"github.com/omec-project/util/httpwrapper"
)

// HandleNSSAIAvailabilityPost - Creates subscriptions for notification about updates to NSSAI availability information
func HandleNSSAIAvailabilityPost(request *httpwrapper.Request) *httpwrapper.Response {
	logger.Nssaiavailability.Infof("Handle NSSAIAvailabilityPost")

	createData := request.Body.(models.NssfEventSubscriptionCreateData)

	// TODO: If NF consumer is not authorized to update NSSAI availability, return ProblemDetails with code 403 Forbidden

	response, problemDetails := NSSAIAvailabilityPostProcedure(createData)

	if response != nil {
		// TODO: Based on TS 29.531 5.3.2.3.1, add location header
		stats.IncrementNssfNssaiAvailabilitySubscriptionsStats("subscribe", "", request.Params["nfId"], "SUCCESS")
		return httpwrapper.NewResponse(http.StatusCreated, nil, response)
	} else if problemDetails != nil {
		stats.IncrementNssfNssaiAvailabilitySubscriptionsStats("subscribe", "", request.Params["nfId"], "FAILURE")
		return httpwrapper.NewResponse(int(problemDetails.Status), nil, problemDetails)
	}
	problemDetails = &models.ProblemDetails{
		Status: http.StatusForbidden,
		Cause:  "UNSPECIFIED",
	}
	return httpwrapper.NewResponse(http.StatusForbidden, nil, problemDetails)
}
