// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF
 *
 * Network Slice Selection Function
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"context"
	"fmt"
	"os"

	"github.com/omec-project/nssf/logger"
	"github.com/omec-project/nssf/service"
	"github.com/urfave/cli/v3"
)

var NSSF = &service.NSSF{}

func main() {
	app := &cli.Command{}
	app.Name = "nssf"
	logger.AppLog.Infoln(app.Name)
	app.Usage = "Network Slice Selection Function"
	app.UsageText = "nssf -cfg <nssf_config_file.conf>"
	app.Action = action
	app.Flags = NSSF.GetCliCmd()

	if err := app.Run(context.Background(), os.Args); err != nil {
		logger.AppLog.Fatalf("NSSF run error: %v", err)
	}
}

func action(ctx context.Context, c *cli.Command) error {
	if err := NSSF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	NSSF.Start()

	return nil
}
