// Copyright 2019 free5GC.org
//
// SPDX-License-Identifier: Apache-2.0
//

/*
 * NSSF
 *
 * Network Slice Selection Function
 *
 * API version: 1.0.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"fmt"
	"os"

	"github.com/omec-project/nssf/logger"
	"github.com/omec-project/nssf/service"
	"github.com/urfave/cli"
	"go.uber.org/zap"
)

var NSSF = &service.NSSF{}

var appLog *zap.SugaredLogger

func init() {
	appLog = logger.AppLog
}

func main() {
	app := cli.NewApp()
	app.Name = "nssf"
	appLog.Infoln(app.Name)
	app.Usage = "-free5gccfg common configuration file -nssfcfg nssf configuration file"
	app.Action = action
	app.Flags = NSSF.GetCliCmd()

	if err := app.Run(os.Args); err != nil {
		appLog.Errorf("NSSF Run Error: %v", err)
	}
}

func action(c *cli.Context) error {
	if err := NSSF.Initialize(c); err != nil {
		logger.CfgLog.Errorf("%+v", err)
		return fmt.Errorf("failed to initialize")
	}

	NSSF.Start()

	return nil
}
