// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NS Selection

NSSF Network Slice Selection Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 2.3.0-alpha.3

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package nsselection

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nssf/logger"
	"github.com/omec-project/nssf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Get /network-slice-information
// Retrieve the Network Slice Selection Information
func HTTPNSSelectionGet(c *gin.Context) {
	logger.Nsselection.Infoln("Handle Get /network-slice-information")
	req := httpwrapper.NewRequest(c.Request, nil)

	rsp := producer.HandleNSSelectionGet(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.HandlerLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
