// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NSSAI Availability

NSSF NSSAI Availability Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package nssaiavailability

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nssf/logger"
)

// Post /:request.body#/nfNssaiAvailabilityUri
func HTTPNssaiAvailabilityNotificationRequestBodyNfNssaiAvailabilityUriPost(c *gin.Context) {
	logger.Nssaiavailability.Warnln("Handle Post /:request.body#/nfNssaiAvailabilityUri is not implemented")
	c.String(http.StatusNotImplemented, "501 not implemented")
}
