// Copyright (c) 2026 Intel Corporation
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NSSAI Availability

NSSF NSSAI Availability Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package nssaiavailability

import (
	"github.com/gin-gonic/gin"
	"github.com/omec-project/nssf/logger"
)

// Options /nssai-availability
// Discover communication options supported by NSSF for NSSAI Availability
func HTTPNSSAIAvailabilityOptions(c *gin.Context) {
	detail := "Handle Options /nssai-availability is not implemented"
	logger.Nssaiavailability.Warnln(detail)
	writeNotImplementedProblem(c, detail)
}
