// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NSSAI Availability

NSSF NSSAI Availability Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package nssaiavailability

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nssf/logger"
	"github.com/omec-project/nssf/plugin"
	"github.com/omec-project/nssf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/models"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Delete /nssai-availability/:nfId
// Deletes an already existing S-NSSAIs per TA provided by the NF service consumer (e.g AMF)
func HTTPNSSAIAvailabilityDelete(c *gin.Context) {
	logger.Nssaiavailability.Infoln("Handle Delete /nssai-availability/:nfId")
	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["nfId"] = c.Params.ByName("nfId")

	rsp := producer.HandleNSSAIAvailabilityDelete(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.HandlerLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Patch /nssai-availability/:nfId
// Updates an already existing S-NSSAIs per TA provided by the NF service consumer (e.g AMF)
func HTTPNSSAIAvailabilityPatch(c *gin.Context) {
	logger.Nssaiavailability.Infoln("Handle Patch /nssai-availability/:nfId")
	var nssaiAvailabilityUpdateInfo plugin.PatchDocument

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.HandlerLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&nssaiAvailabilityUpdateInfo, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.HandlerLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, nssaiAvailabilityUpdateInfo)
	req.Params["nfId"] = c.Params.ByName("nfId")

	rsp := producer.HandleNSSAIAvailabilityPatch(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.HandlerLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}

// Put /nssai-availability/:nfId
// Updates/replaces the NSSF with the S-NSSAIs the NF service consumer (e.g AMF)supports per TA
func HTTPNSSAIAvailabilityPut(c *gin.Context) {
	logger.Nssaiavailability.Infoln("Handle Put /nssai-availability/:nfId")
	var nssaiAvailabilityInfo models.NssaiAvailabilityInfo

	requestBody, err := c.GetRawData()
	if err != nil {
		problemDetail := utils.ProblemDetailsSystemFailure(err.Error())
		logger.HandlerLog.Errorf("Get Request Body error: %+v", err)
		c.JSON(http.StatusInternalServerError, problemDetail)
		return
	}

	err = openapi.Decode(&nssaiAvailabilityInfo, requestBody, "application/json")
	if err != nil {
		problemDetail := "[Request Body] " + err.Error()
		rsp := utils.ProblemDetailsMalformedRequestSyntax(problemDetail)
		logger.HandlerLog.Errorln(problemDetail)
		c.JSON(http.StatusBadRequest, rsp)
		return
	}

	req := httpwrapper.NewRequest(c.Request, nssaiAvailabilityInfo)
	req.Params["nfId"] = c.Params.ByName("nfId")

	rsp := producer.HandleNSSAIAvailabilityPut(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.HandlerLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
