// Copyright (c) 2026 Intel Corporation
// Copyright 2019 free5GC.org
// SPDX-License-Identifier: Apache-2.0

/*
NSSF NSSAI Availability

NSSF NSSAI Availability Service.
© 2024, 3GPP Organizational Partners (ARIB, ATIS, CCSA, ETSI, TSDSI, TTA, TTC).
All rights reserved.

API version: 1.3.0-alpha.6

Authors: Aether SD-Core team
Contact: dev@lists.aetherproject.org

Generated by: OpenAPI Generator (https://openapi-generator.tech)
*/

package nssaiavailability

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/omec-project/nssf/logger"
	"github.com/omec-project/nssf/producer"
	"github.com/omec-project/openapi/v2"
	"github.com/omec-project/openapi/v2/utils"
	"github.com/omec-project/util/httpwrapper"
)

// Patch /nssai-availability/subscriptions/:subscriptionId
// updates an already existing NSSAI availability notification subscription
func HTTPNSSAIAvailabilitySubModifyPatch(c *gin.Context) {
	detail := "Handle Patch /nssai-availability/subscriptions/:subscriptionId is not implemented"
	logger.Nssaiavailability.Infoln(detail)
	writeNotImplementedProblem(c, detail)
}

// Delete /nssai-availability/subscriptions/:subscriptionId
// Deletes an already existing NSSAI availability notification subscription
func HTTPNSSAIAvailabilityUnsubscribe(c *gin.Context) {
	logger.Nssaiavailability.Infoln("Handle Delete /nssai-availability/subscriptions/:subscriptionId")

	req := httpwrapper.NewRequest(c.Request, nil)
	req.Params["subscriptionId"] = c.Params.ByName("subscriptionId")

	rsp := producer.HandleNSSAIAvailabilityUnsubscribe(req)

	responseBody, err := openapi.SetBody(rsp.Body, "application/json")
	if err != nil {
		logger.HandlerLog.Errorln(err)
		problemDetails := utils.ProblemDetailsSystemFailure(err.Error())
		c.JSON(http.StatusInternalServerError, problemDetails)
	} else {
		c.Data(rsp.Status, "application/json", responseBody.Bytes())
	}
}
